export { default as WelcomeSection } from './WelcomeSection/WelcomeSection'
export { default as AboutSection } from './AboutSection/AboutSection'
export { default as TeamSection } from './TeamSection/TeamSection'
export { default as GamesSection } from './GamesSection/GamesSection'
export { default as InViewportDiv } from './InViewportDiv'
export { default as Animated } from './Animated'
export { default as TheFooter } from './TheFooter/TheFooter'
